import React, { useState, useEffect } from "react";
import { Button } from "reactstrap";
import useRazorpay from "react-razorpay";
import { RAZOR_KEY } from "../../common/ConstantString";
import { useSearchParams } from "react-router-dom";
import axios from "../../API/axios";
import toast from "react-hot-toast";
// import axiosInstance from "../../API/axios";
function RazorPay({ buttName, amountPy, hotelNa, logo,sendData,setShow,setMessage,getPaymentData,paymentFid}) {
  // console.log("amt", amountPy, typeof amountPy);
  const Razorpay = useRazorpay();

const [searchParams] = useSearchParams();
const lnk = searchParams.get("lnk");
const token = searchParams.get("xn");
const login = searchParams.get("lid");
const payment_folio_id=paymentFid;
console.log('paymentFid',payment_folio_id);
// console.log("Link-iD",lnk);
// console.log("Token",token);
// console.log("LoginID",login);
// const [show,setShow] = useState(true);
// const handleShow=()=>setShow(true);
  //payment method {abdul}

  //   const razorpayOptions = {
  //     key: "YOUR_RAZORPAY_KEY",
  //     amount: "AMOUNT_IN_Paise",
  //     currency: "INR",
  //     name: "Your Company Name",
  //     description: "Product description",
  //     image: "https://cdn.razorpay.com/logos/XXXXXX.png", // URL of company logo or image
  //     order_id: "order_EMBFqjDHEEn80l", //Order ID generated by Razorpay
  //     handler: function (response) {
  //       alert(response.razorpay_payment_id);
  //     },
  //     prefill: {
  //       name: "Your Name",
  //       email: "your.email@example.com",
  //       contact: "9999999999",
  //     },
  //     notes: {
  //       address: "Razorpay Corporate Office",
  //     },
  //     theme: {
  //       color: "#F37254",
  //     },
  //   };
  // const [orderId, setOrderId] = useState("");
  const [paymentDetails,setPaymentDetails] = useState('');
  // const [paymentFid,setPaymentFid]=useState('');
  const [payResJson,setPayResJson]=useState(''); 

  // const guestDetails = async () =>{
  //   try {
  //     const result = await axios.get(`paymentlink/get/${lnk}`,{
  //       headers: {
  //         LoginId:login,
  //         Token:token,
  //       }
  //         })
  //         console.log("Result",result);
  //         const data = result.data[0][0]
  //         setPaymentDetails(data);
  //         setPaymentFid(data.PaymentFolioID);
  //         setPayResJson(data.PaymentResponseJSON);
  //         PaymentFolioID = data.PaymentFolioID;

  //   } catch (error) {
  //     console.log(error)
  //   }
  // }

  
  // console.log("PaymentFolioID",PaymentFolioID);
  // console.log("PayresponseJson",payResJson);
  

  useEffect(() => {
       try {
         axios.get(`paymentlink/get/${lnk}`,{
          headers: {
            LoginId:login,
            Token:token,
          }
         })

         .then(res => { 
         console.log("Resjkjkk",res.data[0][0])
         setPaymentDetails(res.data[0][0]);
         
         }).
         catch(err => {
          console.error(err)
         })


       } catch (error) {
        console.log(error)
       }
      //  guestDetails();
       sendData = handleOnlinePay();
  }, []);

 

  const ProcessPayment =(response)=> {   
    axios.post(`/paymentlink/payment`,response,{
      headers:{
        LoginId:login,
        Token:token,
      }
    })
    .then((response) => { // Success Response from Razor Pay
      console.log("Responseee",response)
      response.status;
      if(response.status===200){
        toast.success("Payment is Done")
        getPaymentData()
        setMessage("successfully")

      }
      // else{
      //   toast.error("Paymnt is Failed",{position:"top-center"})
        
      // }
      
    }).
    catch(err => {
     console.error(err)
    })
  }
  



  const handleOnlinePay = async () => {
    const options = {
      key: RAZOR_KEY, // Enter the Key ID generated from the Dashboard
      amount:amountPy * 100, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
      currency: "INR",
      name: hotelNa,
      description: "Test Transaction",
      // callback_url: "https://checkout.razorpay.com/v1/checkout.js",
      // redirect : false,
      // redirect_url: "https://checkout.razorpay.com",
      image: logo,
      //   order_id: "1", //This is a sample Order ID. Pass the `id` obtained in the response of createOrder().
      handler: function (response) {
        const objBody={
          Status:'Active',
          PaymentLinkID:lnk,
          PaymentFolioID:payment_folio_id,
          PaymentResponseJSON:"Status\":\"Success"
            
        }
        // console.log("Successs",objBody);
        ProcessPayment(objBody)
      //  console.log("OBJBODY", objBody)

      },
      prefill: {
        name: "Piyush Garg",
        email: "youremail@example.com",
        contact: "9999999999",
      },
      notes: {
        address: "Razorpay Corporate Office",
      },
      theme: {
        color: "#3399cc",
      },

    };
 
    const rzp1 = new Razorpay(options);

    rzp1.on("payment.failed", function (response) { // Failure Response From Razor Pay
      alert("payment failed");
      let objBody = {
        Status: 'Inactive',
        PaymentLinkID:lnk,
          PaymentFolioID:payment_folio_id,
          PaymentResponseJSON: "Status\":\"Failed",

      }
      
      ProcessPayment(objBody)
    });
      // alert(response.error.description);
      // alert(response.error.source);
      // alert(response.error.step);
      // alert(response.error.reason);
      // alert(response.error.metadata.order_id);
      // alert(response.error.metadata.payment_id);
    console.log("dfjdfjidfijdjsdfkmdjkfdfhjkfdkf", rzp1);

    rzp1.open();
  };
  
 

  // const objBody={
  //   Status:'Active',
  //   PaymentLinkID:lnk,
  //   PaymentFolioID:paymentFid,
  //   PaymentResponseJSON:payResJson,
      
  // }
  // const ProcessPayment =(response)=> {   
  //   axios.post(`/paymentlink/payment`,objBody,{
  //     headers:{
  //       LoginId:login,
  //       Token:token,
  //     }
  //   })
  //   .then((response) => { // Success Response from Razor Pay
  //     console.log("Responseee",response)
  //     response.status;
  //     if(response.status===200){
  //       toast.success("Payment is Done",{position:"top-center"})
  //       getPaymentData()
  //       setMessage("successfully")

  //     }
      
  //   }).
  //   catch(err => {
  //    console.error(err)
  //   })
  // }
  

 
   
  return (
    <>
    {paymentDetails.payDate === null ? (
      <Button color="primary" className="me-1" onClick={handleOnlinePay}>
        {buttName}
      </Button>

    ):(
          null
    )}
    </>
  );
}

export default RazorPay;